### ISSUE TITLE
php 7.2 already installed

### ISSUE THREAD

**Issue by nmpribeiro** [Skamasle/sk-php-selector#8]
Hi,

It seems because I already have php 7.2 installed, this plugin is not able to link a new `7.2` version.

```
##########
Start installing aditional php version
##########
Actually you runing php 7.2, so I will skip it
Skip PHP 7.2 actually installed
################################
Aditional PHP versión installed!
```

When I go to vestaCP, I do not find php 7.2 on my list as I would expect. Anyway, I can use the default so... cool!

**Comment by Skamasle** [comment]
Hi

This is normal message, so, script detect default php version, if your php -v return php 7.2 because you upgrade it, script not install php 7.2 if you have php5.6 script not install php 5.6.

So for what you need  php 7.2 in selector if you have it in default ? default version works better than version in php selector so script not install it if you alredy have it in default

**Comment by nmpribeiro** [comment]
Hi @Skamasle I actually understood it a bit after I posted here. So we can close this one.
But before we do that...
> default version works better than version in php selector so script not install it if you alredy have it in default
"works better" Can you expand on that?

**Comment by Skamasle** [comment]
Default can use different templates and additional use fastcgi only so. You
need configure it better from server if not your server may can have memory
isues
